provider:
  name: cycloid
  schema_ref: '#/components/schemas/TerraformProviderCycloid'

resources:
  organization:
    create:
      path: /organizations
      method: POST
    read:
      path: /organizations/{organization_canonical}
      method: GET
    update:
      path: /organizations/{organization_canonical}
      method: PUT
    delete:
      path: /organizations/{organization_canonical}
      method: DELETE
