provider:
  name: cycloid
  schema_ref: '#/components/schemas/TerraformProviderCycloid'

resources:
  credential:
    create:
      path: /organizations/{organization_canonical}/credentials
      method: POST
    read:
      path: /organizations/{organization_canonical}/credentials/{credential_canonical}
      method: GET
    update:
      path: /organizations/{organization_canonical}/credentials/{credential_canonical}
      method: PUT
    delete:
      path: /organizations/{organization_canonical}/credentials/{credential_canonical}
      method: DELETE

