// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_cycloid

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func CycloidProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type CycloidModel struct {
}
