---
# This resource has been edited by had
# This is the base config before edit for info
provider:
  name: "cycloid"
  schema_ref: "#/components/schemas/TerraformProviderCycloid"

data_sources:
  stacks:
    read:
      path: "/organizations/{organization_canonical}/service_catalogs"
      method: "GET"
    schema:
      ignores:
      - "data.cloud_providers.created_at"
      - "data.cloud_providers.id"
      - "data.cloud_providers.updated_at"
      - "data.created_at"
      - "data.id"
      - "data.image"
      - "data.image"
      - "data.import_status"
      - "data.readme"
      - "data.service_catalog_source_canonical"
      - "data.team.created_at"
      - "data.team.id"
      - "data.team.name"
      - "data.team.owner"
      - "data.team.updated_at"
      - "data.updated_at"
      - "page_index"
      - "page_size"
      - "pagination"
