// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_cycloid

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func CycloidProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"jwt": schema.StringAttribute{
				Required: true,
			},
			"organization_canonical": schema.StringAttribute{
				Required: true,
			},
			"url": schema.StringAttribute{
				Required: true,
			},
			"insecure": schema.BoolAttribute{
				Optional:    true,
				Description: "Skip TLS certificate verification (use with self-signed certificates)",
			},
		},
	}
}

type CycloidModel struct {
	Jwt                   types.String `tfsdk:"jwt"`
	OrganizationCanonical types.String `tfsdk:"organization_canonical"`
	Url                   types.String `tfsdk:"url"`
	Insecure              types.Bool   `tfsdk:"insecure"`
}
