// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_organization_api_key

import (
	"context"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func OrganizationAPIKeyResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Description:         "Manages an organization API key in Cycloid.",
		MarkdownDescription: "Manages an organization API key in Cycloid.",
		Attributes: map[string]schema.Attribute{
			"organization_canonical": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A canonical of an organization.",
				MarkdownDescription: "A canonical of an organization.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(3, 100),
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-z0-9]+[a-z0-9\\-_]+[a-z0-9]+$"), ""),
				},
			},
			"canonical": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A canonical of the API key. Auto-generated from the name if omitted.",
				MarkdownDescription: "A canonical of the API key. Auto-generated from the name if omitted.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(3, 100),
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-z0-9]+[a-z0-9\\-_]+[a-z0-9]+$"), ""),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "A human-readable name for the API key.",
				MarkdownDescription: "A human-readable name for the API key.",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(3),
				},
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A description of the API key.",
				MarkdownDescription: "A description of the API key.",
			},
			"owner": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "User canonical of the API key owner. Defaults to the authenticated user.",
				MarkdownDescription: "User canonical of the API key owner. Defaults to the authenticated user.",
			},
			"rules": schema.ListNestedAttribute{
				Required:            true,
				Description:         "Permission rules for the API key. Immutable after creation — changes force recreation.",
				MarkdownDescription: "Permission rules for the API key. Immutable after creation — changes force recreation.",
				PlanModifiers: []planmodifier.List{
					listForceNewPlanModifier{},
				},
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"action": schema.StringAttribute{
							Required:            true,
							Description:         "The action this rule applies to. Supports globs like `*` or `**`.",
							MarkdownDescription: "The action this rule applies to. Supports globs like `*` or `**`.",
						},
						"effect": schema.StringAttribute{
							Required:            true,
							Description:         `The effect of the rule. Only "allow" is supported.`,
							MarkdownDescription: `The effect of the rule. Only "allow" is supported.`,
							Validators: []validator.String{
								stringvalidator.OneOf("allow"),
							},
						},
						"resources": schema.ListAttribute{
							Optional:            true,
							Computed:            true,
							ElementType:         types.StringType,
							Description:         "The list of resources this rule applies to.",
							MarkdownDescription: "The list of resources this rule applies to.",
						},
					},
				},
			},
			"token": schema.StringAttribute{
				Computed:            true,
				Sensitive:           true,
				Description:         "The JWT API key token. Only populated once, at creation time. Store it securely — it cannot be retrieved afterwards.",
				MarkdownDescription: "The JWT API key token. Only populated once, at creation time. Store it securely — it cannot be retrieved afterwards.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"last_seven": schema.StringAttribute{
				Computed:            true,
				Description:         "The last seven characters of the API key token, for identification.",
				MarkdownDescription: "The last seven characters of the API key token, for identification.",
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The internal numeric ID of the API key.",
				MarkdownDescription: "The internal numeric ID of the API key.",
			},
		},
	}
}

// RuleModel represents a single permission rule on an API key.
type RuleModel struct {
	Action    types.String `tfsdk:"action"`
	Effect    types.String `tfsdk:"effect"`
	Resources types.List   `tfsdk:"resources"`
}

// OrganizationAPIKeyModel is the Terraform state model for the organization_api_key resource.
type OrganizationAPIKeyModel struct {
	OrganizationCanonical types.String `tfsdk:"organization_canonical"`
	Canonical             types.String `tfsdk:"canonical"`
	Name                  types.String `tfsdk:"name"`
	Description           types.String `tfsdk:"description"`
	Owner                 types.String `tfsdk:"owner"`
	Rules                 types.List   `tfsdk:"rules"`
	Token                 types.String `tfsdk:"token"`
	LastSeven             types.String `tfsdk:"last_seven"`
	ID                    types.Int64  `tfsdk:"id"`
}
